export const countries = [
    { name: "Saudi Arabia", code: "SA" },
    { name: "Egypt", code: "EG" },
    { name: "United Arab", code: "AE" },
    { name: "Kuwait", code: "KW" },
    { name: "Qatar", code: "QA" },
    { name: "Bahrain", code: "BH" },
    { name: "Oman", code: "OM" },
    { name: "Jordan", code: "JO" },
    { name: "Lebanon", code: "LB" },
    { name: "Iraq", code: "IQ" },
    { name: "Syria", code: "SY" },
    { name: "Yemen", code: "YE" },
    { name: "Morocco", code: "MA" },
    { name: "Algeria", code: "DZ" },
    { name: "Tunisia", code: "TN" },
    { name: "Libya", code: "LY" },
    { name: "Sudan", code: "SD" },
    { name: "Somalia", code: "SO" },
    { name: "Comoros", code: "KM" },
    { name: "Djibouti", code: "DJ" },
    { name: "Mauritania", code: "MR" },
    { name: "Australia", code: "AU" },
    { name: "Brazil", code: "BR" },
    { name: "China", code: "CN" },
    { name: "France", code: "FR" },
    { name: "Germany", code: "DE" },
    { name: "India", code: "IN" },
    { name: "Japan", code: "JP" },
    { name: "Spain", code: "ES" },
    { name: "United States", code: "US" },
  ];